[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = { 
    \   'colorscheme': 'wombat'
    \}
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

# Lang

[[plugins]] # Haml
repo  = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = '''
    let g:vim_markdown_frontmatter = 1
    let g:vim_markdown_math = 1
'''

[[plugins]] # Golang
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]] # ruby
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]] # Elixier
repo = 'elixir-editors/vim-elixir'
on_ft = 'ex'

[[plugins]] # Elixier
repo = 'slashmili/alchemist.vim'
depends = 'vim-elixir'
on_ft = 'ex'

[[plugins]] # javascript
repo = 'pangloss/vim-javascript'
on_ft = 'js'

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'
hook_add = '''
    set helplang=ja,en
'''

# Colors

[[plugins]] # colorscheme
repo = 'flazz/vim-colorschemes'

